[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5174"
additional_redirect_urls = ["http://localhost:5174", "http://localhost:5173", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

[edge_runtime]
enabled = true

[functions.cloudinary-poses]
verify_jwt = false

[functions.imagekit-poses]
verify_jwt = false